spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edusnooker?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      
  liquibase:
    contexts: prod

