spring:
  datasource:
    url: jdbc:mysql://mysql:3306/edusnooker
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      
  liquibase:
    contexts: prod

