jwt:
  secret: 'sfc45v{@Crwerc]34cAEWRCGWEafcwAsfmo34rcfc]%^2gvtyv45$FF'

spring:
  liquibase:
    change-log: classpath:db/liquibase/master.xml

  jpa:
    show-sql: true

#server:
#  error:
#    whitelabel:
#      enabled: false

#  mvc:
#    throw-exception-if-no-handler-found: true
#    static-path-pattern: /static

