spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/edusnooker?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      
  liquibase:
    contexts: prod

